# Generated by Django 4.2.14 on 2024-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="dislike_comment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="like_comment",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
