# Generated by Django 4.2.14 on 2024-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_comment_dislike_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="num_likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
