# Generated by Django 4.2.14 on 2024-08-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved_comment",
        ),
    ]
