# Generated by Django 4.2.14 on 2024-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
