# Generated by Django 4.2.14 on 2024-08-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="document",
        ),
        migrations.CreateModel(
            name="PostDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docuemnt",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
