# Generated by Django 4.2.14 on 2024-08-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_post_document_postdocuments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdocuments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="blog.post",
            ),
        ),
    ]
