# Generated by Django 4.2.14 on 2024-08-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_postdocuments_post"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostDocuments",
            new_name="PostDocument",
        ),
    ]
